name: Labeler

on:
  pull_request:
    branches:
    - master

label:

    runs-on: ubuntu-latest, windows-latest, macOS-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
